const colors = {
  light: {
    text: "#ffffff",
    tint: "#DC143C",
    background: "#000000",
    foreground: "#ffffff",
    card: "#0a0a0a",
    cardForeground: "#ffffff",
    primary: "#DC143C",
    primaryForeground: "#ffffff",
    secondary: "#1a1a1a",
    secondaryForeground: "#ffffff",
    muted: "#1e1e1e",
    mutedForeground: "#999999",
    accent: "#F59E0B",
    accentForeground: "#000000",
    destructive: "#ff4444",
    destructiveForeground: "#ffffff",
    border: "#1f1f1f",
    input: "#1f1f1f",
  },
  dark: {
    text: "#ffffff",
    tint: "#DC143C",
    background: "#000000",
    foreground: "#ffffff",
    card: "#0a0a0a",
    cardForeground: "#ffffff",
    primary: "#DC143C",
    primaryForeground: "#ffffff",
    secondary: "#1a1a1a",
    secondaryForeground: "#ffffff",
    muted: "#1e1e1e",
    mutedForeground: "#999999",
    accent: "#F59E0B",
    accentForeground: "#000000",
    destructive: "#ff4444",
    destructiveForeground: "#ffffff",
    border: "#1f1f1f",
    input: "#1f1f1f",
  },
  radius: 4,
};

export default colors;
